controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    
    

diff_cont:
  ros__parameters:
    odom_frame_id: odom
    base_frame_id: base_link
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheels_per_side: 1
    wheel_separation: 0.3429 # shortest distance between the left and right wheels (inner to inner)
    wheel_radius: 0.1016
    open_loop: false
    enable_odom_tf: true
    use_stamped_vel: false
    state_interfaces:
      - position
      - velocity
