# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    slider_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:

      - shoulder_joint
      - upperarm_joint
      - forearm_joint
      - wrist_joint_1
      - wrist_joint_2
      - wrist_joint_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

slider_controller:
  ros__parameters:
    joints: 
      - slider
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity