# Default initial positions for robot's ros2_control fake system

initial_positions:
  Revolute 35: 0
  Revolute 38: 0
  Revolute 39: 0
  Revolute 40: 0
  Revolute 41: 0
  Revolute 42: 0
  Slider 29: 0
  Slider 30: 0
  Slider 33: 0