# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - slider_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Revolute 35
      - Revolute 41
      - Revolute 38
      - Revolute 39
      - Revolute 40
      - Revolute 42
  slider_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Slider 33
  gripper_controller:
    type: GripperCommand
    joints:
      - Slider 29
      - Slider 30
    action_ns: gripper_cmd
    default: true