# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    slider_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    odom_frame_id: odom
    base_frame_id: base_link
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheels_per_side: 1
    wheel_separation: 0.45 # shortest distance between the left and right wheels (inner to inner)
    wheel_radius: 0.1016
    open_loop: false
    enable_odom_tf: true
    use_stamped_vel: false

arm_controller:
  ros__parameters:
    joints:
      - Revolute 35
      - Revolute 41
      - Revolute 38
      - Revolute 39
      - Revolute 40
      - Revolute 42
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
slider_controller:
  ros__parameters:
    joint: Slider 33
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - Slider 29
      - Slider 30
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity